apiVersion: v1
kind: Pod
metadata:
   name: frontend
labels:
    project: roboshop
    component: frontend
    environment: dev
    version: v4

spec:
  containers:
    - name: frontend
      image: frontend

