apiVersion: v1
kind: Pod
metadata:
  name: env-intro
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: TRAINER
          value: "venkatsai"
        - name: COURSE
          value: "devsecops"