apiVersion: v1
kind: Pod
metadata:
  name: env-intro
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: roboshop
          value: "Hello from the environment"
        - trainer: venkatsai
          course: devsecops
          