apiVersion: v1
kind: pod
metadata:
  name: pod-config
  labels:
    course: "k8s"
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: configmap-demo