apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  labels:   # These labels are used to register this pod with service
      project: roboshop
      component: frontend
      environment: dev
spec:
   containers:
   - name: nginx
     image: nginx