apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  
spec:
  type: LoadBlancer
  selector:
    project: roboshop
    component: frontend
    environment: pre-prod
    purpose: load-blancer
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 
      nodeport: 32500
