apiVersion: v1
kind: pod
metadata:
  name: service-lb
  labels:   # These labels are used to register this pod with service
      project: roboshop
      component: frontend
      environment: pre-prod
      purpose: load-blancer
spec:
   containers:
   - name: nginx
     image: nginx