apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
   # these are  deployment  labels
  labels:
    purpose: deployment-demo
    project: roboshop

spec: # depolyment spec
  replicas: 3
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: deployment-demo
      project: roboshop   
  template:
    metadata:
    ## pod labels
      labels:
        purpose: deployment-demo
        project: roboshop  
    spec: #pod spec
      containers:
      - name: nginx
        image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    purpose: deployment-demo
    project: roboshop  
  ports:
    - protocol: TCP
      port: 80 ## service port
      targetPort: 80 ## container port