apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
   # these are replica set labels
  labels:
    project: roboshop
    component: frontend
    environment: dev

spec:
  replicas: 3
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: frontend
      environment: dev  
  template:
    metadata:
    ## pod labels
      labels:
        project: roboshop
        component: frontend
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  clusterIP: None ## Headless serive
  selector:
     project: roboshop
     component: frontend
     environment: dev
  ports:
    - protocol: TCP
      port: 80 ## service port
      targetPort: 80 ## container port

        