apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling
   # these are  deployment  labels
  labels:
    purpose: rolling-update
    project: roboshop

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # add extra
      maxUnavailable: 1 # remove old
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: rolling-update
      project: roboshop   
  template:
    metadata:
    ## pod labels
      labels:
        purpose: rolling-update
        project: roboshop  
    spec:
      containers:
      - name: nginx
        image: nginx:1.25

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    purpose: rolling-update
    project: roboshop  
  ports:
    - protocol: TCP
      port: 80 ## service port
      targetPort: 80 ## container port