apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: roboshop
   # these are  deployment  labels
  labels:
    purpose: deployment-demo
    project: roboshop

spec:
  replicas: 5
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: deployment-demo
      project: roboshop   
  template:
    metadata:
    ## pod labels
      labels:
        purpose: deployment-demo
        project: roboshop  
    spec:
      containers:
      - name: nginx
        image: nginx

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      purpose: deployment-demo
      project: roboshop 